### ISSUE TITLE
Instantiate under (Async.ToAsync)

### ISSUE THREAD

**Issue by imneil24** [AmartanIlmarinen/UnityAsyncRoutines#2]
Hello 

Is it possible to execute instantiate object behind the process using **yield return Async.ToAsync;**.
I was trying to instantiate Gameobject bunch of items on first load by not freezing the app.

Thank You

**Comment by TorVestergaard** [comment]
Unfortunately, this cannot be done, as you cannot use Unity APIs like instantiating GameObjects from outside the main game thread. However, if execution throttling on the main game thread is enabled, then async routines running on the game thread only have a bit of execution time available, and will be throttled automatically - thus lessening the performance impact.

```
Async.ThrottleGameLoopExecutionTime = true;
Async.ExecutionTimePerFrame = 0.025; // 25 ms available per frame
```
